export const GET_SESSIONS = 'GET_SESSIONS';
export const GET_SESSION = 'GET_SESSION';
export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const PURGE_ATTENDANCE = 'PURGE_ATTENDANCE';
