export const GET_SESSIONS = 'GET_SESSIONS';
export const GET_SESSION = 'GET_SESSION';
export const GET_MEMBERS = 'GET_MEMBERS';
export const PURGE_ATTENDANCE_DTO = 'PURGE_ATTENDANCE_DTO';
export const INSERT_ATTENDANCE = 'INSERT_ATTENDANCE';
export const GET_ATTENDANCE_DTO = 'GET_ATTENDANCE_DTO';
